
DROP TABLE IF EXISTS `bot_command`;
CREATE TABLE IF NOT EXISTS `bot_command` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `security` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `category` varchar(64) DEFAULT NULL,
  `subcategory` varchar(64) DEFAULT NULL,
  `help` longtext DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=250 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC COMMENT='Bot and Playerbot Chat Commands';


/*!40000 ALTER TABLE `bot_command` DISABLE KEYS */;
INSERT INTO `bot_command` (`id`, `name`, `security`, `category`, `subcategory`, `help`) VALUES
	(1, '.ahbot item <item id>', 3, 'System Commands', 'AHBot', 'Check current ahbot configuration for a specific item ID.'),
	(2, '.ahbot item <item id> <item value> <chance> <min amount> <max amount>', 3, 'System Commands', 'AHBot', 'Override ahbot config with custom price, chance (1–100) and amount range.'),
	(3, '.ahbot item <item id> reset', 3, 'System Commands', 'AHBot', 'Reset ahbot configuration for a specific item.'),
	(4, '.bot add <bot name>', 0, 'System Commands', 'Bot Management', 'Add a bot to the game; must belong to your account or guild.'),
	(5, '.bot ammo <bot name>', 0, 'System Commands', 'Bot Management', 'Give relevant ammo to specified bot.'),
	(6, '.bot consumables <bot name>', 0, 'System Commands', 'Bot Management', 'Give consumables to the bot.'),
	(7, '.bot enchants <bot name>', 0, 'System Commands', 'Bot Management', 'Enchant bot gear appropriately for its class/spec.'),
	(8, '.bot food <bot name>', 0, 'System Commands', 'Bot Management', 'Give food and drink to the bot.'),
	(9, '.bot gear <bot name>', 0, 'System Commands', 'Bot Management', 'Randomize bot gear; max level based on RandomGearMaxLevel.'),
	(10, '.bot init <bot name>', 0, 'System Commands', 'Bot Management', 'Level bot to your level, randomize gear, learn spells, and give items.'),
	(11, '.bot learn <bot name>', 0, 'System Commands', 'Bot Management', 'Teach all spells to the bot for its level.'),
	(12, '.bot pet <bot name>', 0, 'System Commands', 'Bot Management', 'Initialize bot pet (hunter tame / warlock train).'),
	(13, '.bot potions <bot name>', 0, 'System Commands', 'Bot Management', 'Give potion reagents to the bot.'),
	(14, '.bot prepare <bot name>', 0, 'System Commands', 'Bot Management', 'Give ammo, food, potions, reagents, and consumables.'),
	(15, '.bot reagents <bot name>', 0, 'System Commands', 'Bot Management', 'Give reagents to the bot.'),
	(16, '.bot remove <bot name>', 0, 'System Commands', 'Bot Management', 'Remove bot from the world.'),
	(17, '.bot train <bot name>', 0, 'System Commands', 'Bot Management', 'Make bot learn all available class spells.'),
	(18, '.bot upgrade <bot name>', 0, 'System Commands', 'Bot Management', 'Upgrade bot gear to better quality.'),
	(19, '.rndbot diff', 1, 'System Commands', 'Server Tools', 'Show average and max difficulty (server load indicator).'),
	(20, '.rndbot reload', 3, 'System Commands', 'Server Tools', 'Reload all bot configuration live from aiplayerbot.conf.'),
	(21, '.rndbot stats', 1, 'System Commands', 'Server Tools', 'Display statistics about active bots.'),
	(22, '.rndbot teleport', 3, 'System Commands', 'Server Tools', 'Teleport all bots randomly based on level.'),
	(23, 'accept [quest link]', 0, 'Chat Commands', 'Quest Interaction', 'Tell the bot to accept a specific quest from selected NPC.'),
	(24, 'accept all', 0, 'Chat Commands', 'Quest Interaction', 'Tell the bot to accept all available quests.'),
	(25, 'doquest [quest link/quest id]', 0, 'Chat Commands', 'Quest Interaction', 'Make bot focus on a chosen quest.'),
	(26, 'drop <quest name>', 0, 'Chat Commands', 'Quest Interaction', 'Ask bot to drop a specific quest.'),
	(27, 'drop all', 0, 'Chat Commands', 'Quest Interaction', 'Ask bot to abandon all quests.'),
	(28, 'share [quest link]', 0, 'Chat Commands', 'Quest Interaction', 'Ask bot to share a quest.'),
	(29, 'quests', 0, 'Chat Commands', 'Quest Interaction', 'Show bot’s quest progress.'),
	(30, 'quests <co/in/all>', 0, 'Chat Commands', 'Quest Interaction', 'Filter quest list (completed/incomplete/all).'),
	(31, 'attack', 0, 'Chat Commands', 'Combat', 'Tell bot to attack your current target.'),
	(32, 'attack rti', 0, 'Chat Commands', 'Combat', 'Attack assigned raid target.'),
	(33, 'flee', 0, 'Chat Commands', 'Combat', 'Bot flees and goes passive.'),
	(34, 'pull', 0, 'Chat Commands', 'Combat', 'Tell bot to pull current target.'),
	(35, 'pull rti', 0, 'Chat Commands', 'Combat', 'Pull assigned raid target.'),
	(36, 'cast <spell name>', 0, 'Chat Commands', 'Combat', 'Cast the specified spell.'),
	(37, 'summon', 3, 'Chat Commands', 'Combat', 'Force summon and revive bot.'),
	(38, 'rti <raid icon>', 0, 'Chat Commands', 'Combat', 'Assign raid target for attack.'),
	(39, 'rti cc <raid icon>', 0, 'Chat Commands', 'Combat', 'Assign raid target for CC.'),
	(40, 'reset ai', 3, 'Chat Commands', 'Combat', 'Reset bot AI and reload defaults.'),
	(41, 'follow', 0, 'Chat Commands', 'Movement', 'Tell bot to follow you.'),
	(42, 'follow target <name>', 0, 'Chat Commands', 'Movement', 'Follow specific player.'),
	(43, 'guard', 0, 'Chat Commands', 'Movement', 'Guard current area.'),
	(44, 'stay', 0, 'Chat Commands', 'Movement', 'Hold position.'),
	(45, 'go npc <npc name>', 0, 'Chat Commands', 'Movement', 'Travel to a specific NPC.'),
	(46, 'go zone <location name>', 0, 'Chat Commands', 'Movement', 'Travel to a location or zone.'),
	(47, 'home', 0, 'Chat Commands', 'Movement', 'Set home at selected innkeeper.'),
	(48, 'revive', 0, 'Chat Commands', 'Movement', 'Revive at nearest spirit healer.'),
	(49, 'release', 0, 'Chat Commands', 'Movement', 'Release spirit when dead.'),
	(50, 'rtsc save <position name>', 1, 'Chat Commands', 'Movement', 'Save named RTSC position.'),
	(51, 'rtsc go <position name>', 1, 'Chat Commands', 'Movement', 'Go to saved RTSC position.'),
	(52, 'rtsc unsave <position name>', 1, 'Chat Commands', 'Movement', 'Delete saved RTSC position.'),
	(53, 'bank', 0, 'Chat Commands', 'Inventory', 'List items in bot bank.'),
	(54, 'bank [item link]', 0, 'Chat Commands', 'Inventory', 'Deposit item to bank.'),
	(55, 'bank -[item link]', 0, 'Chat Commands', 'Inventory', 'Withdraw item from bank.'),
	(56, 'items', 0, 'Chat Commands', 'Inventory', 'List items in bags.'),
	(57, 'items ah', 0, 'Chat Commands', 'Inventory', 'Show items bot plans to sell on AH.'),
	(58, 'keep [item link]', 0, 'Chat Commands', 'Inventory', 'Mark item to keep.'),
	(59, 'keep equip [item link]', 0, 'Chat Commands', 'Inventory', 'Keep item equipped.'),
	(60, 'keep none [item link]', 0, 'Chat Commands', 'Inventory', 'Remove keep status.'),
	(61, 's [item link]', 0, 'Chat Commands', 'Inventory', 'Sell specified item.'),
	(62, 'b [item link]', 0, 'Chat Commands', 'Inventory', 'Buy specified item.'),
	(63, 'mail ?', 0, 'Chat Commands', 'Inventory', 'List pending mail.'),
	(64, 'mail take', 0, 'Chat Commands', 'Inventory', 'Retrieve mail or items.'),
	(65, 'sendmail [item link]', 0, 'Chat Commands', 'Inventory', 'Send item to player.'),
	(66, 'repair', 0, 'Chat Commands', 'Inventory', 'Repair bot gear at vendor.'),
	(67, 'join', 0, 'Chat Commands', 'Group and Guild', 'Join player group.'),
	(68, 'leave', 0, 'Chat Commands', 'Group and Guild', 'Leave current group or raid.'),
	(69, 'give leader', 0, 'Chat Commands', 'Group and Guild', 'Give leader privileges to player.'),
	(70, 'guild leave', 0, 'Chat Commands', 'Group and Guild', 'Leave current guild.'),
	(71, 'lfg', 0, 'Chat Commands', 'Group and Guild', 'Auto-find group based on role.'),
	(72, 'trainer', 0, 'Chat Commands', 'Training', 'List trainable skills.'),
	(73, 'trainer learn', 0, 'Chat Commands', 'Training', 'Learn all trainable skills.'),
	(74, 'talents', 0, 'Chat Commands', 'Training', 'Report current talent build.'),
	(75, 'talents auto', 0, 'Chat Commands', 'Training', 'Auto-choose build.'),
	(76, 'talents list', 0, 'Chat Commands', 'Training', 'List all available builds.'),
	(77, 'talents <build name>', 0, 'Chat Commands', 'Training', 'Switch to a specific build.'),
	(78, 'help', 0, 'Chat Commands', 'Utility', 'Show bot help menu.'),
	(79, 'who', 0, 'Chat Commands', 'Utility', 'Get bot info: spec, item level, etc.'),
	(80, 'stats', 0, 'Chat Commands', 'Utility', 'Show bot stats: gold, xp, bags.'),
	(81, 'skill', 0, 'Chat Commands', 'Utility', 'List all skill levels.'),
	(82, 'skill [name]', 0, 'Chat Commands', 'Utility', 'Show specific skill.'),
	(83, 'skill unlearn [name]', 0, 'Chat Commands', 'Utility', 'Unlearn profession.'),
	(84, 'faction', 0, 'Chat Commands', 'Utility', 'List factions and reputation.'),
	(85, 'faction [name]', 0, 'Chat Commands', 'Utility', 'Show specific faction rep.'),
	(86, 'faction +atwar [name]', 0, 'Chat Commands', 'Utility', 'Flag faction at war.'),
	(87, 'faction -atwar [name]', 0, 'Chat Commands', 'Utility', 'Remove war flag.'),
	(88, 'outfit ?', 0, 'Chat Commands', 'Utility', 'List available outfits.'),
	(89, 'outfit <name> equip', 0, 'Chat Commands', 'Utility', 'Equip outfit.'),
	(90, 'outfit <name> reset', 0, 'Chat Commands', 'Utility', 'Reset outfit.'),
	(91, 'outfit <name> update', 0, 'Chat Commands', 'Utility', 'Update outfit.'),
	(92, 'emote <emote name>', 0, 'Chat Commands', 'Utility', 'Perform emote.'),
	(93, 'rndbot reload', 3, 'Chat Commands', 'GM Utility', 'Reload bot configuration live.'),
	(94, 'rndbot teleport', 3, 'Chat Commands', 'GM Utility', 'Teleport all bots randomly.'),
	(95, 'rndbot stats', 1, 'Chat Commands', 'GM Utility', 'Display bot statistics.'),
	(96, 'rndbot diff', 1, 'Chat Commands', 'GM Utility', 'Show average and max difficulty.'),
	(97, '@dps', 0, 'Chat Filters', 'Role', 'Selects all bots with DPS role.'),
	(98, '@nodps', 0, 'Chat Filters', 'Role', 'Selects bots that are not DPS.'),
	(99, '@tank', 0, 'Chat Filters', 'Role', 'Selects tank role bots.'),
	(100, '@notank', 0, 'Chat Filters', 'Role', 'Selects bots that are not tanks.'),
	(101, '@heal', 0, 'Chat Filters', 'Role', 'Selects healer role bots.'),
	(102, '@warrior', 0, 'Chat Filters', 'Class', 'Select all warrior bots.'),
	(103, '@paladin', 0, 'Chat Filters', 'Class', 'Select all paladin bots.'),
	(104, '@hunter', 0, 'Chat Filters', 'Class', 'Select all hunter bots.'),
	(105, '@rogue', 0, 'Chat Filters', 'Class', 'Select all rogue bots.'),
	(106, '@priest', 0, 'Chat Filters', 'Class', 'Select all priest bots.'),
	(107, '@shaman', 0, 'Chat Filters', 'Class', 'Select all shaman bots.'),
	(108, '@mage', 0, 'Chat Filters', 'Class', 'Select all mage bots.'),
	(109, '@warlock', 0, 'Chat Filters', 'Class', 'Select all warlock bots.'),
	(110, '@druid', 0, 'Chat Filters', 'Class', 'Select all druid bots.'),
	(111, '@group<number>', 0, 'Chat Filters', 'Group', 'Select bots in a specific group (e.g. @group1).'),
	(112, '@group1-3', 0, 'Chat Filters', 'Group', 'Select bots in a group range (e.g. @group1-3).'),
	(113, '@nogroup', 0, 'Chat Filters', 'Group', 'Select bots not in a group.'),
	(114, '@leader', 0, 'Chat Filters', 'Group', 'Select bots that are group leaders.'),
	(115, '@raid', 0, 'Chat Filters', 'Group', 'Select bots in a raid group.'),
	(116, '@noraid', 0, 'Chat Filters', 'Group', 'Select bots not in a raid group.'),
	(117, '@rleader', 0, 'Chat Filters', 'Group', 'Select bots that are raid leaders.'),
	(118, '@<level>', 0, 'Chat Filters', 'Level', 'Select bots of a specific level (e.g. @10 or @1-10).'),
	(119, '@tier1', 0, 'Chat Filters', 'Gear', 'Bots with average gear comparable to Tier 1.'),
	(120, '@tier2-3', 0, 'Chat Filters', 'Gear', 'Bots with average gear comparable to Tier 2–3.'),
	(121, '@tier4', 0, 'Chat Filters', 'Gear', 'Bots with average gear comparable to Tier 4.'),
	(122, '@tier5', 0, 'Chat Filters', 'Gear', 'Bots with average gear comparable to Tier 5.'),
	(123, '@tier6', 0, 'Chat Filters', 'Gear', 'Bots with average gear comparable to Tier 6.'),
	(124, '@tier7', 0, 'Chat Filters', 'Gear', 'Bots with average gear comparable to Tier 7.'),
	(125, '@tier8', 0, 'Chat Filters', 'Gear', 'Bots with average gear comparable to Tier 8.'),
	(126, '@tier9', 0, 'Chat Filters', 'Gear', 'Bots with average gear comparable to Tier 9.'),
	(127, '@tier10', 0, 'Chat Filters', 'Gear', 'Bots with average gear comparable to Tier 10.'),
	(128, '@ranged', 0, 'Chat Filters', 'Combat', 'Select bots that use ranged attacks.'),
	(129, '@melee', 0, 'Chat Filters', 'Combat', 'Select bots that use melee attacks.'),
	(130, '@dead', 0, 'Chat Filters', 'Combat', 'Select bots that are dead.'),
	(131, '@nodead', 0, 'Chat Filters', 'Combat', 'Select bots that are alive.'),
	(132, '@guild', 0, 'Chat Filters', 'Guild', 'Select all bots in a guild.'),
	(133, '@guild=<name>', 0, 'Chat Filters', 'Guild', 'Select bots in specific guild.'),
	(134, '@noguild', 0, 'Chat Filters', 'Guild', 'Select bots not in any guild.'),
	(135, '@gleader', 0, 'Chat Filters', 'Guild', 'Select bots that are guild leaders.'),
	(136, '@rank=<rank name>', 0, 'Chat Filters', 'Guild', 'Select bots with specific guild rank.'),
	(137, '@<spec>', 0, 'Chat Filters', 'Strategy', 'Select bots of a specific spec (e.g. @fury).'),
	(138, '@<class>', 0, 'Chat Filters', 'Strategy', 'Select bots of a specific class (e.g. @mage).'),
	(139, '@nc=<strategy>', 0, 'Chat Filters', 'Strategy', 'Bots with <strategy> active in non-combat.'),
	(140, '@nonc=<strategy>', 0, 'Chat Filters', 'Strategy', 'Bots without <strategy> in non-combat.'),
	(141, '@co=<strategy>', 0, 'Chat Filters', 'Strategy', 'Bots with <strategy> in combat.'),
	(142, '@noco=<strategy>', 0, 'Chat Filters', 'Strategy', 'Bots without <strategy> in combat.'),
	(143, '@react=<strategy>', 0, 'Chat Filters', 'Strategy', 'Bots with <strategy> in reaction state.'),
	(144, '@noreact=<strategy>', 0, 'Chat Filters', 'Strategy', 'Bots without <strategy> in reaction state.'),
	(145, '@dead=<strategy>', 0, 'Chat Filters', 'Strategy', 'Bots with <strategy> while dead.'),
	(146, '@nodead=<strategy>', 0, 'Chat Filters', 'Strategy', 'Bots without <strategy> while dead.'),
	(147, '@needrepair', 0, 'Chat Filters', 'State', 'Bots whose durability is below 20%.'),
	(148, '@outside', 0, 'Chat Filters', 'State', 'Bots currently outside of instances.'),
	(149, '@inside', 0, 'Chat Filters', 'State', 'Bots currently inside an instance.'),
	(150, '@azeroth', 0, 'Chat Filters', 'Location', 'Bots located in Azeroth overworld.'),
	(151, '@eastern kingdoms', 0, 'Chat Filters', 'Location', 'Bots located in Eastern Kingdoms.'),
	(152, '@dun morogh', 0, 'Chat Filters', 'Location', 'Bots located in Dun Morogh.'),
	(153, '@use=[itemlink]', 0, 'Chat Filters', 'Item Usage', 'Bots that have use for an item.'),
	(154, '@sell=[itemlink]', 0, 'Chat Filters', 'Item Usage', 'Bots that will sell or auction an item.'),
	(155, '@need=[itemlink]', 0, 'Chat Filters', 'Item Usage', 'Bots that will roll Need on an item.'),
	(156, '@greed=[itemlink]', 0, 'Chat Filters', 'Item Usage', 'Bots that will roll Greed on an item.'),
	(157, '@frost', 0, 'Chat Filters', 'Talent Spec', 'Bots whose primary spec is Frost.'),
	(158, '@holy', 0, 'Chat Filters', 'Talent Spec', 'Bots whose primary spec is Holy.'),
	(159, '@random', 0, 'Chat Filters', 'Random', 'Selects 50% of bots at random.'),
	(160, '@random=25', 0, 'Chat Filters', 'Random', 'Selects 25% of bots at random.'),
	(161, '@fixedrandom', 0, 'Chat Filters', 'Random', 'Selects fixed 50% subset of bots.'),
	(162, '@fixedrandom=25', 0, 'Chat Filters', 'Random', 'Selects fixed 25% subset of bots.'),
	(163, 'aoe', 0, 'Strategies', 'Combat', 'Enable use of area-of-effect abilities.'),
	(164, 'boost', 0, 'Strategies', 'Combat', 'Enable use of cooldowns and boost abilities.'),
	(165, 'buff', 0, 'Strategies', 'Support', 'Enable buffing allies.'),
	(166, 'cc', 0, 'Strategies', 'Combat', 'Enable crowd-control spells like Polymorph or Fear.'),
	(167, 'cure', 0, 'Strategies', 'Support', 'Enable curing or cleansing debuffs from allies.'),
	(168, 'heal', 0, 'Strategies', 'Support', 'Enable healing behavior for heal-capable classes.'),
	(169, 'loot', 0, 'Strategies', 'Utility', 'Enable looting corpses and chests.'),
	(170, 'offdps', 0, 'Strategies', 'Hybrid', 'Allow healers to DPS when idle.'),
	(171, 'offheal', 0, 'Strategies', 'Hybrid', 'Allow DPS to perform supplemental healing.'),
	(172, 'pull', 0, 'Strategies', 'Combat', 'Allow initiating pulls at range.'),
	(173, 'pvp', 0, 'Strategies', 'Combat', 'Enable PvP combat.'),
	(174, 'tank', 0, 'Strategies', 'Combat', 'Enable tanking behavior for tank classes.'),
	(175, 'wait for attack', 0, 'Strategies', 'Combat', 'Bot waits before engaging in combat.'),
	(176, 'nc +<strategy>', 0, 'Strategies', 'Non-Combat', 'Add a non-combat strategy.'),
	(177, 'nc -<strategy>', 0, 'Strategies', 'Non-Combat', 'Remove a non-combat strategy.'),
	(178, 'nc ?', 0, 'Strategies', 'Non-Combat', 'List current non-combat strategies.'),
	(179, 'co +<strategy>', 0, 'Strategies', 'Combat', 'Add a combat strategy.'),
	(180, 'co -<strategy>', 0, 'Strategies', 'Combat', 'Remove a combat strategy.'),
	(181, 'co ?', 0, 'Strategies', 'Combat', 'List current combat strategies.'),
	(182, 'de +<strategy>', 0, 'Strategies', 'Dead', 'Add a dead-state strategy.'),
	(183, 'de -<strategy>', 0, 'Strategies', 'Dead', 'Remove a dead-state strategy.'),
	(184, 'de ?', 0, 'Strategies', 'Dead', 'List current dead-state strategies.'),
	(185, 'react +<strategy>', 0, 'Strategies', 'Reaction', 'Add a reaction strategy.'),
	(186, 'react -<strategy>', 0, 'Strategies', 'Reaction', 'Remove a reaction strategy.'),
	(187, 'react ?', 0, 'Strategies', 'Reaction', 'List current reaction strategies.'),
	(188, 'all +<strategy>', 0, 'Strategies', 'Global', 'Add a strategy to all states (combat, non-combat, dead, react).'),
	(189, 'all -<strategy>', 0, 'Strategies', 'Global', 'Remove a strategy from all states.'),
	(190, 'all ?', 0, 'Strategies', 'Global', 'List all currently active strategies.'),
	(191, 'stay', 0, 'Macros', 'Behavior', 'Bot holds current position until further orders.'),
	(192, 'guard', 0, 'Macros', 'Behavior', 'Bot guards area and returns after combat.'),
	(193, 'free', 0, 'Macros', 'Behavior', 'Bot moves independently during combat.'),
	(194, 'follow', 0, 'Macros', 'Behavior', 'Bot follows the player or target.'),
	(195, 'follow target <name>', 0, 'Macros', 'Behavior', 'Follow a specific target in group or raid.'),
	(196, 'do follow', 0, 'Macros', 'Behavior', 'Force follow even during combat.'),
	(197, '+follow', 0, 'Macros', 'Behavior', 'Enable automatic following.'),
	(198, '-follow', 0, 'Macros', 'Behavior', 'Disable automatic following.'),
	(199, '+threat', 0, 'Macros', 'Behavior', 'Increase threat generation focus.'),
	(200, 'home', 0, 'Macros', 'Behavior', 'Set home at selected innkeeper.'),
	(201, '+pvp', 0, 'Macros', 'Behavior', 'Enable PvP combat behavior.'),
	(202, '+wait for attack', 0, 'Macros', 'Behavior', 'Wait before starting combat with delay.'),
	(203, 'nc +rpg', 0, 'Macros', 'Behavior', 'Enable roleplay behavior.'),
	(204, 'nc -rpg', 0, 'Macros', 'Behavior', 'Disable roleplay behavior.'),
	(205, '+travel', 0, 'Macros', 'Behavior', 'Enable travel mode behavior.'),
	(206, '-travel', 0, 'Macros', 'Behavior', 'Disable travel mode behavior.'),
	(207, 'co +boost', 0, 'Macros', 'Combat Setup', 'Enable use of cooldowns and boosts.'),
	(208, 'co +pull', 0, 'Macros', 'Combat Setup', 'Enable ranged pulling behavior.'),
	(209, 'co +tank', 0, 'Macros', 'Combat Setup', 'Enable tanking AI behavior.'),
	(210, 'co +ranged', 0, 'Macros', 'Combat Setup', 'Switch to ranged combat.'),
	(211, 'co -ranged', 0, 'Macros', 'Combat Setup', 'Switch to melee combat.'),
	(212, '+dps assist', 0, 'Macros', 'Combat Setup', 'Assist the main DPS target.'),
	(213, '+tank assist', 0, 'Macros', 'Combat Setup', 'Assist the tank’s target.'),
	(214, 'cast <spellname>', 0, 'Macros', 'Combat Setup', 'Force-cast a spell by name.'),
	(215, 'focus heal +<name>', 0, 'Macros', 'Combat Setup', 'Assign healing focus to target(s).'),
	(216, 'focus heal none', 0, 'Macros', 'Combat Setup', 'Clear all healing focus targets.'),
	(217, 'buff target +<name>', 0, 'Macros', 'Combat Setup', 'Buff specified target(s).'),
	(218, 'buff target none', 0, 'Macros', 'Combat Setup', 'Clear buff targets.'),
	(219, 'boost target +<name>', 0, 'Macros', 'Combat Setup', 'Assign boost targets (e.g. Innervate).'),
	(220, 'boost target none', 0, 'Macros', 'Combat Setup', 'Clear boost targets.'),
	(221, 'rtsc save <position>', 0, 'Macros', 'Movement', 'Save custom RTSC movement position.'),
	(222, 'rtsc go <position>', 0, 'Macros', 'Movement', 'Move to saved RTSC position.'),
	(223, 'rtsc unsave <position>', 0, 'Macros', 'Movement', 'Delete saved RTSC position.'),
	(224, 'rtsc select', 0, 'Macros', 'Movement', 'Select bot for manual RTSC control.'),
	(225, 'rtsc cancel', 0, 'Macros', 'Movement', 'Cancel RTSC selection.'),
	(226, 'go npc <name>', 0, 'Macros', 'Movement', 'Travel to specific NPC (requires free mode).'),
	(227, 'go zone <location>', 0, 'Macros', 'Movement', 'Travel to specific zone (requires free mode).'),
	(228, '/p @tank @heal all -travel,+free,+follow', 0, 'Macros', 'Group', 'Form raid follow setup for tanks and healers.'),
	(229, '/p @group1 @tank co +tank,+aoe,+boost', 0, 'Macros', 'Group', 'Assign tank setup to group 1.'),
	(230, '/p @group2 @heal co +heal,+cleanse,+boost', 0, 'Macros', 'Group', 'Assign healer setup to group 2.'),
	(231, '/p @group3 @dps all +aoe,+boost,+threat', 0, 'Macros', 'Group', 'Assign DPS setup to group 3.'),
	(232, '/p @heal all +rpg,+buff,+heal', 0, 'Macros', 'Group', 'Enable roleplay and buffs for healers.'),
	(233, '/p all +follow', 0, 'Macros', 'Group', 'Make all bots follow.'),
	(234, '/p all -follow,+free', 0, 'Macros', 'Group', 'Release all bots from follow.'),
	(235, '/p all +stay', 0, 'Macros', 'Group', 'Hold all bots in position.'),
	(236, '/p all +guard', 0, 'Macros', 'Group', 'Set all bots to guard mode.'),
	(237, '/p @group1 co +tank,+threat,+boost,+pull', 0, 'Macros', 'Group', 'Tank setup for group 1.'),
	(238, '/p @group2 co +heal,+aoe,+cleanse', 0, 'Macros', 'Group', 'Healer setup for group 2.'),
	(239, '/p @group3 co +aoe,+boost,+melee', 0, 'Macros', 'Group', 'DPS setup for group 3.'),
	(240, '/p @heal focus heal +<Name>', 0, 'Macros', 'Group', 'Assign healing focus.'),
	(241, '/p @heal focus heal none', 0, 'Macros', 'Group', 'Clear all healing focus.'),
	(242, '/p @tank buff target +<Name>', 0, 'Macros', 'Group', 'Assign buff target for tanks.'),
	(243, '/p @tank buff target none', 0, 'Macros', 'Group', 'Remove tank buff targets.'),
	(244, '/p @tank boost target +<Name>', 0, 'Macros', 'Group', 'Assign boost targets for tanks.'),
	(245, '/p all +rpg,+travel', 0, 'Macros', 'Group', 'Enable travel and roleplay for all.'),
	(246, '/p all -rpg,-travel,+free', 0, 'Macros', 'Group', 'Disable travel and roleplay, enable free movement.'),
	(247, '/p @tank go npc <name>', 0, 'Macros', 'Group', 'Command tanks to move to an NPC.'),
	(248, '/p @tank go zone <location>', 0, 'Macros', 'Group', 'Command tanks to move to a zone.'),
	(249, '/p @group1 @heal home', 0, 'Macros', 'Group', 'Healers in group 1 set home.');
/*!40000 ALTER TABLE `bot_command` ENABLE KEYS */;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
