###################################################################################################################
# BALANCING SETTINGS
#
#    Balancing.Enable
#        Enable balancing module
#        Default: 1 (enable)
#                 0 (disable)
#
###################################################################################################################

Balancing.Enable = 1