###################################################################################################################
# CUSTOM20 SETTINGS
#
#    Custom20.Enable
#        Enable Custom20 module
#        Default: 1 (enable)
#                 0 (disable)
#
###################################################################################################################

Custom20.Enable = 1