[AiPlayerbotConf]
ConfVersion=2020072501

AiPlayerbot.Enabled = 1
AiPlayerbot.RandomBotAutologin = 1
AiPlayerbot.RandomBotLoginAtStartup = 1
AiPlayerbot.ExplicitDbStoreSave = 0
AiPlayerbot.DeleteRandomBotAccounts = 0
AiPlayerbot.BotAutologin = 0
AiPlayerbot.RandomBotJoinLfg = 1
AiPlayerbot.RandomBotJoinBG = 1
AiPlayerbot.RandomBotAutoJoinBG = 0
AiPlayerbot.PreQuests = 0
AiPlayerbot.RandomBotAutoCreate = 1

AiPlayerbot.MinRandomBots = 250
AiPlayerbot.MaxRandomBots = 250
AiPlayerbot.RandomBotMinLevel = 1
AiPlayerbot.RandomBotMaxLevel = 60

AiPlayerbot.RandomBotAccountPrefix = RNDBOT
AiPlayerbot.RandomBotAccountCount = 80
AiPlayerbot.RandomBotGuildCount = 12
AiPlayerbot.RandomBotArenaTeamCount = 0
AiPlayerbot.DeleteRandomBotGuilds = 0
AiPlayerbot.DeleteRandomBotArenaTeams = 0

AiPlayerbot.RandomBotMaps = 0,1
AiPlayerbot.RandomBotTeleportTeleportMinInterval = 7200
AiPlayerbot.RandomBotTeleportTeleportMaxInterval = 172800

AiPlayerbot.RandomGearLoweringChance = 0.15
AiPlayerbot.RandomGearMaxLevel = 100
AiPlayerbot.RandomGearMaxDiff = 9
AiPlayerbot.RandomGearUpgradeEnabled = 0
AiPlayerbot.RandomGearTabards = 0
AiPlayerbot.RandomGearTabardsChance = 0.1
AiPlayerbot.RandomGearTabardsReplaceGuild = 0
AiPlayerbot.RandomGearTabardsUnobtainable = 0
AiPlayerbot.RandomGearBlacklist = 0

AiPlayerbot.RollBadItemsWithPlayer = 0
AiPlayerbot.RandomBotMaxLevelChance = 0.15
AiPlayerbot.RandomBotRpgChance = 0.20
AiPlayerbot.TurnInRpg = 0
AiPlayerbot.GlobalSoundEffects = 0
AiPlayerbot.ShowProgressBars = 1
AiPlayerbot.RandombotsWalkingRPG = 0

AiPlayerbot.MinRandomBotInWorldTime = 1800
AiPlayerbot.MaxRandomBotInWorldTime = 10800
AiPlayerbot.MinRandomBotRandomizeTime = 900
AiPlayerbot.MaxRandomRandomizeTime = 7200
AiPlayerbot.RandomBotCountChangeMinInterval = 300
AiPlayerbot.RandomBotCountChangeMaxInterval = 900
AiPlayerbot.RandomBotsMaxLoginsPerInterval = 25
