[MangosdConf]
ConfVersion=2025040601

RealmID = 4
DataDir = "/srv/vmangos/data"
LogsDir = "/var/log/mangos"
HonorDir = "/var/log/mangos"

LoginDatabase.Info              = "127.0.0.1;3306;sppuser;spppass;vmangosrealmd"
LoginDatabase.Connections       = 1
LoginDatabase.WorkerThreads     = 1
WorldDatabase.Info              = "127.0.0.1;3306;sppuser;spppass;vmangos"
WorldDatabase.Connections       = 1
WorldDatabase.WorkerThreads     = 1
CharacterDatabase.Info          = "127.0.0.1;3306;sppuser;spppass;vmangoscharacters"
CharacterDatabase.Connections   = 1
CharacterDatabase.WorkerThreads = 1
LogsDatabase.Info               = "127.0.0.1;3306;sppuser;spppass;vmangoslogs"
LogsDatabase.Connections        = 1
LogsDatabase.WorkerThreads      = 1
Database.AliveCheckInternal     = 600

WorldServerPort = 8085
BindIP = "0.0.0.0"

LogLevel = 2
LogTime = 1
LogFile = "Server.log"
LogTimestamp = 1
LogFileLevel = 2
LogFilter_Pathfinding = 0

PlayerLimit = 0
PlayerHardLimit = 0
Compression.Level = 1
GridUnload = 1
MapUpdate.Threads = 3
vmap.enableLOS = 1
vmap.enableHeight = 1
vmap.enableIndoorCheck = 1
mmap.enabled = 1
PathFinder.OptimizePath = 1
PathFinder.NormalizeZ = 1

Console.Enable = 0
Ra.Enable = 1
Ra.IP = "0.0.0.0"
Ra.Port = 3443
Ra.MinLevel = 3
Ra.Secure = 1
Ra.Restricted = 1

PlayerBot.ShowInWhoList = 1
PartyBot.MaxBots = 0
PartyBot.SkipChecks = 0
PartyBot.AutoEquip = 1
BattleBot.AutoEquip = 1
PartyBot.RandomGearLevelDifference = 10

AHBot.Enable = 1
AHBot.ah.fid = 120
AHBot.itemcount = 2000
