[RealmdConf]
ConfVersion=2024091701

LoginDatabaseInfo = "127.0.0.1;3306;sppuser;spppass;vmangosrealmd"
LogsDir = "/var/log/mangos"
PatchesDir = "/srv/vmangos/patches"
RealmServerPort = 3724
BindIP = "0.0.0.0"

LogLevel.Console = 2
LogLevel.File = 2
LogTime = 1
LogFile = "Realmd.log"
LogTimestamp = 1
LogFileLevel = 2

PidFile = ""
MaxPingTime = 30
MinRealmListDelay = 1
RealmsStateUpdateDelay = 20
WrongPass.MaxCount = 0
WrongPass.BanTime = 600
